### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by decathorpe**
I'm one of the package maintainers of desed in Fedora. I noticed that the dependencies are starting to fall a bit behind the latest available versions, so I thought I'd try helping update them. My changes are split into multiple commits to hopefully make it easier to review them. As far as I can tell, rendering and behaviour are unchanged when comparing "before" and "after" these changes.

1. I fixed some warnings that are printed by newer versions of rust and clippy, and replaced the `cfg(target_os = ...)` identifier from `"darwin"` (which isn't a value recognized by rust) to `"macos"`.
2. I enabled deprecation warnings in clap v3 and migrated away from all deprecated APIs (this is recommended by clap before attempting to migrate from clap v3 to v4).
3. Ported from clap v3 to v4. This required some additional small code changes.
4. Ported from tui (which is unmaintained) to its maintained replacement, ratatui, and updated it and crossterm to the latest available version. Both required some small code changes.

Feel free to take and apply any individual parts of this set of commits individually, if that helps. :)

### CODE REVIEW

**Comment by SoptikHa2** [comment]
It looks great, I tried it on a few files, and it seems to work fine.

Thanks for the update and for the code style fixes, it looks much better now!

**Review by SoptikHa2 — APPROVED** [review]

**Comment by decathorpe** [comment]
Awesome, thanks for the quick response!

Do you plan to also publish 1.2.2 to crates.io?

**Comment by SoptikHa2** [comment]
Will try to get to it this evening (CET). I should also finally rewrite the parser sometime as well 😄

**Comment by SoptikHa2** [comment]
Published!

**Pull request merged**
